### ISSUE TITLE
 Error detected while processing function on NVIM

### ISSUE THREAD

**Issue by yriveiro** [TaDaa/vimade#12]
# Description

Every time I open NVIM I hit this issue:

```python
    Error detected while processing function vimade#CheckWindows[3]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/yriveiro/.config/nvim/plugged/vimade/lib/vimade.py", line 25, in update
    fader.update(nextState)
  File "/Users/yriveiro/.config/nvim/plugged/vimade/lib/fader.py", line 36, in update
    status = GLOBALS.update()
  File "/Users/yriveiro/.config/nvim/plugged/vimade/lib/global_state.py", line 120, in update
    basefg = colors.fromHexStringToRGB(basefg)
AttributeError: module 'colors' has no attribute 'fromHexStringToRGB'
Error detected while processing function vimade#Init[7]..vimade#CheckWindows[3]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/yriveiro/.config/nvim/plugged/vimade/lib/vimade.py", line 25, in update
    fader.update(nextState)
  File "/Users/yriveiro/.config/nvim/plugged/vimade/lib/fader.py", line 36, in update
    status = GLOBALS.update()
  File "/Users/yriveiro/.config/nvim/plugged/vimade/lib/global_state.py", line 131, in update
    basebg = colors.fromHexStringToRGB(basebg)
Press ENTER or type command to continue
Error detected while processing function vimade#Init[7]..vimade#CheckWindows[3]..provider#python3#Call:
line   18:
AttributeError: module 'colors' has no attribute 'fromHexStringToRGB'
```

# Environment
- OSX Mojave
- NVIM v0.3.4
  - Build type: Release
  - LuaJIT 2.0.5

**Comment by TaDaa** [comment]
Thanks for the report -- I think its hitting a name collision on colors.py with modules installed with pip -- will look into it

**Comment by TaDaa** [comment]
Think it should behave now, try again when you have a chance.

**Comment by yriveiro** [comment]
Fixed!
