### ISSUE TITLE
Errors in Command mode

### ISSUE THREAD

**Issue by pnetherwood** [TaDaa/vimade#36]
When you go into Command Mode (q:) vimade produces an error. This is down to win_goto() not being supported in Command Mode.

```
Error detected while processing function vimade#CheckWindows:
line    3:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/myth/.vim/plugged/vimade/lib/vimade/bridge.py", line 32, in update
    fader.update(nextState)
  File "/home/myth/.vim/plugged/vimade/lib/vimade/fader.py", line 208, in update
    fadeWin(win)
  File "/home/myth/.vim/plugged/vimade/lib/vimade/fader.py", line 356, in fadeWin
    vim.command('noautocmd call win_gotoid('+winid+')')
vim.error: Vim(call):E11: Invalid in command-line window; <CR> executes, CTRL-C quits
E171: Missing :endif
Error detected while processing function vimade#Tick:
line   13:
E605: Exception not caught: Vimade Error=1\nVim(py3):vim.error: Vim(call):E11: Invalid in command-line window; <CR> executes, CTRL-C quits
Error detected while processing function vimade#Tick:
line   13:
E605: Exception not caught: Vimade Error=2\nVim(py3):vim.error: Vim(call):E11: Invalid in command-line window; <CR> executes, CTRL-C quits
Error detected while processing function vimade#Tick:
line   13:
E605: Exception not caught: Vimade Error=0\nVim(py3):vim.error: Vim(call):E11: Invalid in command-line window; <CR> executes, CTRL-C quits

```

Ubuntu 16.04 Vim 8.2 and
MSYS2 vim 8.1

**Comment by TaDaa** [comment]
Thanks looking into it, looks like I should be able to detect this and skip processing.  Should have it fixed shortly
