### ISSUE TITLE
problem working with git commits

### ISSUE THREAD

**Issue by kujohn** [TaDaa/vimade#4]
When doing a `git commit`, vim is launched and vimade is causing a bunch of python issues:

```
Error detected while processing function vimade#UnfadeCurrentBuffer:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/abc/.vim/plugged/vimade/lib/vimade.py", line 3, in <module>
    import math
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so, 2): no suitable image found.  Did find:
^I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so: code signature in (/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.                                
Error detected while processing function vimade#Init:
line    2:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function vimade#Init[2]..vimade#CheckWindows:
line    4:
Traceback (most recent call last):
```

**Comment by kujohn** [comment]
Yup, I am on Mojave. Running `vim` works fine. I'll give python3 a shot.

**Comment by TaDaa** [comment]
Any luck with reinstalling python2 or python3?

**Comment by TaDaa** [comment]
Closing for now, but feel free to reopen, I can help you work through possibly removing the libs that are complained about (as long as it’s not all of them)

**Comment by kujohn** [comment]
Tried uninstalling Python 2/3 and then reinstalling, still no dice... 😢 
```
~/src/miyagi-frontend/.git/COMMIT_EDITMSG" 7L, 214C
Error detected while processing function vimade#UnfadeCurrentBuffer:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jku/.vim/plugged/vimade/lib/vimade.py", line 3, in <module>
    import math
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so, 2): no suitable image f
ound.  Did find:
^I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so: code signature in (/Library/Frameworks/Py
thon.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so) not valid for use in process using Library Validation: mapped fil
e has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
Error detected while processing function vimade#Init:
line    2:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function vimade#Init[2]..vimade#CheckWindows:
line    4:
Traceback (most recent call last):
```
