### ISSUE TITLE
pynvim error with fresh install

### ISSUE THREAD

**Issue by kokkonisd** [TaDaa/vimade#80]
Hi, thank your for this plugin!

By doing a fresh install with the latest commit on the `master` branch (51a7c79 at the time of writing), I get the following error whenever I start up neovim post-installation:

```
Error detected while processing VimEnter Autocommands for "*"..script /home/plumtrie/dotfiles/nvim/.config/nvim/plugged/vimade/autoload/vimade.vim[702]..function vimade#Init[20]..vimade#CheckWindows[15]..provider#
python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/plumtrie/dotfiles/nvim/.config/nvim/plugged/vimade/lib/vimade/bridge.py", line 32, in update
    fader.update(nextState)
  File "/home/plumtrie/dotfiles/nvim/.config/nvim/plugged/vimade/lib/vimade/fader.py", line 44, in update
    status = GLOBALS.update()
             ^^^^^^^^^^^^^^^^
  File "/home/plumtrie/dotfiles/nvim/.config/nvim/plugged/vimade/lib/vimade/global_state.py", line 178, in update
    base_fill = colors.getHi(GLOBALS.normal_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plumtrie/dotfiles/nvim/.config/nvim/plugged/vimade/lib/vimade/colors.py", line 29, in getHi
    hi = list(map(lambda x: '' if x == '-1' else int(x), util.eval_and_return('vimade#GetNvimHi('+id+')')))
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pynvim/plugin/script_host.py", line 210, in eval
    obj = self.request("vim_eval", expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pynvim/api/nvim.py", line 199, in request
    res = self._session.request(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/session.py", line 139, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: VimEnter Autocommands for "*"..script /home/plumtrie/dotfiles/nvim/.config/nvim/plugged/vimade/autoload/vimade.vim[702]..function vimade#Init[20]..vimade#CheckWindows[15]..provider#pyt
hon3#Call[18]..vimade#CheckWindows[15]..vimade#GetNvimHi, line 2: Vim(let):E728: Using a Dictionary as a Number
```

I've reverted to ac48ef0, which does not seem to have this issue.
Could you please fix this on `master`?

**Comment by TaDaa** [comment]
Thanks for reporting @kokkonisd ! I'm not able to reproduce this, would you mind posting a minimal vimrc or init.vim with the issue and your Neovim version?

**Comment by kokkonisd** [comment]
Here you go!

init.vim:
```
call plug#begin('~/.config/nvim/plugged')

Plug 'TaDaa/vimade'

call plug#end()
```

Neovim version:
```
$ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by TaDaa** [comment]
Should be fixed now! I didn't realize `??` was only supported recently.
